### ISSUE TITLE
Refresh circle.yml

### ISSUE THREAD

**Issue by stevector** [stevector/example-wordpress-composer#13]
`circle.yml` hasn't been updated recently. I need to compare against https://github.com/pantheon-systems/example-drops-8-composer/blob/master/circle.yml

**Comment by greg-1-anderson** [comment]
Note also that I renamed the commands in the Terminus Build Tools Plugin on the 2.x branch for better consistency.  The 2.x branch still has the original command names as aliases, and the 1.x branch now has the 2.x command names added as aliases. It'd be best to use the new names (example: [build:env:create](https://github.com/pantheon-systems/example-drops-8-composer/blob/63889259eb2f0803b10b8d08db1a40e7f82990c9/circle.yml#L57)) when you refresh.

**Comment by stevector** [comment]
Closed via https://github.com/stevector/example-wordpress-composer/pull/19
