### ISSUE TITLE
Consider a drupalscaffold-like way of doing core installation

### ISSUE THREAD

**Issue by stevector** [stevector/example-wordpress-composer#14]

**Comment by ataylorme** [comment]
Update to download WordPress upstream with `https://github.com/pantheon-systems/WordPress/archive/master.zip`

**Comment by ataylorme** [comment]
Actually we should install from the new repo headed to Packagist.

**Comment by stevector** [comment]
Agreed

**Comment by stevector** [comment]
Yes, I agree https://github.com/pantheon-systems/wordpress-composer is the new answer here. Moved the issue to https://github.com/pantheon-systems/example-wordpress-composer/issues/5
