### ISSUE TITLE
Document Behat tests

### ISSUE THREAD

**Issue by stevector** [stevector/example-wordpress-composer#8]
Right now the test section of CircleCI is not running a real test.

I'd like to use https://github.com/pantheon-systems/pantheon-wordpress-upstream-tests but that makes hard-coded assumptions about file paths. Having `wp/wp-admin` instead of just `wp-admin` causes test fails.

**Comment by stevector** [comment]
Tests are at least passing now on a branch of https://github.com/pantheon-systems/pantheon-wordpress-upstream-tests/tree/handle-wp-subdir--rebase

That branch should either be merged or at least documented before this repo (`example-wordpress-composer`) moves to the `pantheon-systems` org.

**Comment by ataylorme** [comment]
Per our discussion working on converting these to use WordHat and run their default tests rather than the Pantheon Behat tests

**Comment by stevector** [comment]
Merged https://github.com/stevector/example-wordpress-composer/pull/26
